steps:
  - id: "Build Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$_APP_NAME:$SHORT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/$_APP_NAME:latest",
        "--no-cache",
        "./go/",
      ]

  - id: "Push Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$_APP_NAME"]

  - id: "Deploy App"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_APP_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$_APP_NAME:latest",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
      ]

images:
  - "gcr.io/$PROJECT_ID/$_APP_NAME:latest"
tags: ["cloud-builders-community"]
